apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      volumes:
        - name: wordpress
          emptyDir: {}
        - name: wp-content
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}
        
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: wordpress    
            - mountPath: /usr/share/nginx/html/wp-content
              name: wp-content
          env:
            - name: PHP_ENDPOINT
              value: {{ .Values.nginx.phpEndpoint }}
            - name: NGINX_PORT
              value: "{{ .Values.nginx.port }}"
            - name: HOST
              {{- with (first .Values.ingress.hosts) }}
              value: {{ .host }}
              {{- end }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP    

          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}

        - name: {{ .Chart.Name }}-unit
          volumeMounts:
            - mountPath: /opt/wordpress/wp-content
              name: wp-content
            - mountPath: /opt/wordpress-nginx
              name: wordpress
          env:
            - name: WORDPRESS_FORCE_HTTPS
              value: "{{ if eq .Values.wordpress.scheme "https" }}true{{ else }}false{{ end }}"
            - name: WP_AUTO_UPDATE_CORE
              value: "{{ .Values.wordpress.autoUpdateCore }}"
          envFrom:
            - secretRef:
                name: {{ include "wordpress.fullname" . }}-salts
            - secretRef:
                name: {{ .Release.Name | trunc 63 | trimSuffix "-" }}-db

          lifecycle:
            postStart:
              exec:
                command:
                  {{- toYaml .Values.postStart.command | nindent 18 }}          

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: php
              containerPort: 9090
              protocol: TCP

          {{- if .Values.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
