{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- if .Values.persistence.createSnapshot }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ .Values.persistence.dataSource.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  volumeSnapshotClassName: ebs-csi-snapshot-class
  source:
    snapshotHandle: {{ .Values.persistence.snapshotHandle }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.dataSource }}
  dataSource:
    name: {{ .Values.persistence.dataSource.name }}
    kind: {{ .Values.persistence.dataSource.kind | default "VolumeSnapshot" }}
    apiGroup: {{ .Values.persistence.dataSource.apiGroup | default "snapshot.storage.k8s.io" }}
  {{- end }}
{{- end }}
