apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-salts
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" (include "wordpress.fullname" $) "salts")) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $authKey := (get $secretData "WORDPRESS_AUTH_KEY") | default (randAlphaNum 32 | b64enc) }}
  {{- $secureAuthKey := (get $secretData "WORDPRESS_SECURE_AUTH_KEY") | default (randAlphaNum 32 | b64enc) }}
  {{- $loggedInKey := (get $secretData "WORDPRESS_LOGGED_IN_KEY") | default (randAlphaNum 32 | b64enc) }}
  {{- $nonceKey := (get $secretData "WORDPRESS_NONCE_KEY") | default (randAlphaNum 32 | b64enc) }}
  {{- $authSalt := (get $secretData "WORDPRESS_AUTH_SALT") | default (randAlphaNum 32 | b64enc) }}
  {{- $secureAuthSalt := (get $secretData "WORDPRESS_SECURE_AUTH_SALT") | default (randAlphaNum 32 | b64enc) }}
  {{- $loggedInSalt := (get $secretData "WORDPRESS_LOGGED_IN_SALT") | default (randAlphaNum 32 | b64enc) }}
  {{- $nonceSalt := (get $secretData "WORDPRESS_NONCE_SALT") | default (randAlphaNum 32 | b64enc) }}
  WORDPRESS_AUTH_KEY: {{ $authKey | quote }}
  WORDPRESS_SECURE_AUTH_KEY: {{ $secureAuthKey | quote }}
  WORDPRESS_LOGGED_IN_KEY: {{ $loggedInKey | quote }}
  WORDPRESS_NONCE_KEY: {{ $nonceKey | quote }}
  WORDPRESS_AUTH_SALT: {{ $authSalt | quote }}
  WORDPRESS_SECURE_AUTH_SALT: {{ $secureAuthSalt | quote }}
  WORDPRESS_LOGGED_IN_SALT: {{ $loggedInSalt | quote }}
  WORDPRESS_NONCE_SALT: {{ $nonceSalt | quote }}
